name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  dotlottie_loader: ^0.0.4
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_secure_storage: ^9.2.2
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  lottie: ^3.1.3
  provider: ^6.1.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/languages/
    - assets/motions/

flutter_icons:
  android: true
  ios: true
  web: true
  windows: true
  macos: true
  image_path: "assets/icons/redroute.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/redroute.png"
  min_sdk_android: 21
  icon_size: 144
  theme_color: "#232f3b"